---
swagger: "2.0"
info:
  description: "This is a user service api definition"
  version: "1.0.0"
  title: "Station Service"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
schemes:
- "http"
paths:
  /cosme/{cosme_id}:
    get:
      tags:
      - "cosme"
      summary: "Get Cosme By CosmeID"
      operationId: "getCosme"
      produces:
      - "application/json"
      parameters:
      - name: "cosme_id"
        in: "path"
        description: "cosme_id in path"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Cosme"
      x-swagger-router-controller: "Cosme"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Cosme:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      cosmename:
        type: "string"
      category_id:
        type: "integer"
        format: "int64"
      brand_id:
        type: "integer"
        format: "int64"
      item_id:
        type: "integer"
        format: "int64"
      cosme_id:
        type: "integer"
        format: "int64"
      color_id:
        type: "integer"
        format: "int64"
      love_rate:
        type: "integer"
        format: "int64"
      image:
        type: "string"
      pick_rate:
        type: "integer"
        format: "int64"
    example:
    - id: 1
      cosmename: "CANMAKEパーフェクトスタイリストアイズ"
      user_id: 1
      category_id: 1
      brand_id: 1
      item_id: 1
      cosme_id: 1
      color_id: 1
      love_rate: 1
      image: "http://ur0.biz/THYP"
      pick_rate: 1
      created_at: "2000-01-23T04:56:07.000+00:00"
      updated_at: "2000-01-23T04:56:07.000+00:00"
  ApiResponse:
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
